# Generated by Django 3.2.16 on 2022-11-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasa', '0002_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='date',
            field=models.DateTimeField(verbose_name='Дата замера'),
        ),
    ]
